//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTCC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Funcionario_Empresa
    {
        public int idFuncionario { get; set; }
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        public string Empresa { get; set; }
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        [RegularExpression("(^[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2})$", ErrorMessage = "Por favor, preencha o campo no formato: 000.000.000-00")]
        public string CPF { get; set; }
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        [RegularExpression("^([^0-9])*$", ErrorMessage = "Esse campo não deve conter números")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "Esse campo é obrigatório no formato: 00/00/0000")]
        public string Data_Nascimento { get; set; }
        [Required(ErrorMessage = "Esse campo é obrigatório")]
        [RegularExpression("(^[0-9]{2}[.][0-9]{3}[.][0-9]{3}[-][0-9]{1})$", ErrorMessage = "Por favor, preencha o campo no formato: 00.000.000-0")]
        public string RG { get; set; }
    }
}