//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Empresa
    {
        public int idFuncionario { get; set; }
        public string Empresa { get; set; }
        public string Senha { get; set; }
    }
}
