//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoTCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class funcionarioEntities4 : DbContext
    {
        public funcionarioEntities4()
            : base("name=funcionarioEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cadastro_Adm> Cadastro_Adm { get; set; }
        public virtual DbSet<Cadastro_Cidadao> Cadastro_Cidadao { get; set; }
        public virtual DbSet<Cadastro_Empresa> Cadastro_Empresa { get; set; }
        public virtual DbSet<Contato> Contatoes { get; set; }
        public virtual DbSet<Estudante> Estudantes { get; set; }
        public virtual DbSet<Funcionario_Empresa> Funcionario_Empresa { get; set; }
        public virtual DbSet<Login_Adm> Login_Adm { get; set; }
        public virtual DbSet<Login_Empresa> Login_Empresa { get; set; }
    }
}
